#Acts information validation
#do the match between variables name used in the program (db) and variables name displayed
variablesNameDic={}
#name used by the program -> name displayed (to be translated in English)
variablesNameDic["eurlexTitreEn"]="TitreEn"
variablesNameDic["eurlexCodeSectRep01"]="CodeSectRep01"
variablesNameDic["eurlexCodeSectRep02"]="CodeSectRep02"
variablesNameDic["eurlexCodeSectRep03"]="CodeSectRep03"
variablesNameDic["eurlexCodeSectRep04"]="CodeSectRep04"
variablesNameDic["eurlexRepEn1"]="RepEn1"
variablesNameDic["eurlexRepEn2"]="RepEn2"
variablesNameDic["eurlexRepEn3"]="RepEn3"
variablesNameDic["eurlexRepEn4"]="RepEn4"
variablesNameDic["eurlexTypeActe"]="TypeActe"
variablesNameDic["eurlexBaseJuridique"]="BaseJuridique"

variablesNameDic["oeilCommissionPE"]="CommissionPE"
variablesNameDic["oeilEPComAndtTabled"]="EPComAndtTabled"
variablesNameDic["oeilEPComAndtAdopt"]="EPComAndtAdopt"
variablesNameDic["oeilEPVotesFor1"]="EPVotesFor1"
variablesNameDic["oeilEPVotesAgst1"]="EPVotesAgst1"
variablesNameDic["oeilEPVotesAbs1"]="EPVotesAbs1"
variablesNameDic["oeilEPVotesFor2"]="EPVotesFor2"
variablesNameDic["oeilEPVotesAgst2"]="EPVotesAgst2"
variablesNameDic["oeilEPVotesAbs2"]="EPVotesAbs2"
variablesNameDic["oeilGroupePolitiqueRapporteur1"]="GroupePolitiqueRapporteur1"
variablesNameDic["oeilRapporteurPE1"]="RapporteurPE1"
variablesNameDic["oeilEtatMbRapport1"]="EtatMbRapport1"
variablesNameDic["oeilGroupePolitiqueRapporteur2"]="GroupePolitiqueRapporteur2"
variablesNameDic["oeilRapporteurPE2"]="RapporteurPE2"
variablesNameDic["oeilGroupePolitiqueRapporteur3"]="GroupePolitiqueRapporteur3"
variablesNameDic["oeilRapporteurPE3"]="RapporteurPE3"
variablesNameDic["oeilGroupePolitiqueRapporteur4"]="GroupePolitiqueRapporteur4"
variablesNameDic["oeilRapporteurPE4"]="RapporteurPE4"
variablesNameDic["oeilGroupePolitiqueRapporteur5"]="GroupePolitiqueRapporteur5"
variablesNameDic["oeilRapporteurPE5"]="RapporteurPE5"
variablesNameDic["oeilModifPropos"]="ModifPropos"
variablesNameDic["oeilNombreLectures"]="NombreLectures"
variablesNameDic["oeilSignPECS"]="SignPECS"

variablesNameDic["prelexAdoptionProposOrigine"]="AdoptionProposOrigine"
variablesNameDic["prelexComProc"]="ComProc"
variablesNameDic["prelexDGProposition"]="DGProposition"
variablesNameDic["prelexDGProposition2"]="DGProposition2"
variablesNameDic["prelexRespPropos1"]="RespPropos1"
variablesNameDic["prelexRespPropos2"]="RespPropos2"
variablesNameDic["prelexRespPropos3"]="RespPropos3"
variablesNameDic["prelexTransmissionCouncil"]="TransmissionCouncil"
variablesNameDic["prelexNbPointB"]="NbPointB"
variablesNameDic["prelexConsB"]="ConsB"
variablesNameDic["prelexAdoptionConseil"]="AdoptionConseil"
variablesNameDic["prelexNbPointA"]="NbPointA"
variablesNameDic["prelexCouncilA"]="CouncilA"
variablesNameDic["prelexNombreLectures"]="NombreLectures"
